
include: package:flutter_lints/flutter.yaml

linter:
    rules:
        unawaited_futures: true
        omit_local_variable_types: false
        avoid_types_on_closure_parameters: false
        camel_case_types: true
        cancel_subscriptions: true
        comment_references: true
        await_only_futures: true
        exhaustive_cases: true
        avoid_print: false
        # avoid_print is a new lint as of 1.14.  This library uses print to send warnings
        # to the developer, but of course we expect them to be turned off in production
        # code.

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
# linter:
#   rules:
#     - camel_case_types

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false


#  errors:
#        prefer_single_quotes: ignore

#   exclude:
#     - path/to/excluded/files/**
