name: jovial_svg
description: SVG - Robust rendering of Scalable Vector Graphic images, supporting a well-defined profile of SVG and a fast-loading binary storage format.
version: 1.0.6
homepage:  https://bill.jovial.com/

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  xml: ^5.1.0
  args: ^2.0.0
  pedantic: ^1.0.8
  quiver: ^3.0.0
  vector_math: ^2.1.0
  jovial_misc: ^0.8.0
  http: ^0.13.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

executables:
  avd_to_si:
  svg_to_si:

repository: https://github.com/zathras/jovial_svg

issues: https://github.com/zathras/jovial_svg/issues

flutter:

