name: jovial_svg
description: SVG - Robust rendering of Scalable Vector Graphic images, supporting a well-defined profile of SVG and a fast-loading binary storage format.
version: 1.0.2
homepage:  https://github.com/zathras/jovial_svg

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  xml: ^5.1.0
  args: ^2.0.0
  pedantic: ^1.0.8
  quiver: ^3.0.0
  vector_math: ^2.1.0
  jovial_misc: ^0.6.1
  http: ^0.13.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
