name: avd_to_si
description: Converter from Android Vector Drawable to optimized scaling_image format
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  xml: ^5.1.0

dev_dependencies:
  pedantic: ^1.9.0
